include:
  - project: 'general/ci-templates'
    file: 'workflow.gitlab-ci.yml'

  - project: 'general/ci-templates'
    file: 'docker-img.gitlab-ci.yml'


variables:
  DOCKER_IMAGE_NAME: fritzbox-exporter
  DOCKER_NAMESPACE: sealife
  IMG_BUILD_ARGS: --platform linux/amd64 --platform linux/arm64 --platform linux/arm/v7 --platform linux/arm/v6
  IMG_PUSH_LATEST: 'yes'
  IMG_PUSH_UNSTABLE: 'yes' # push every commit to docker hub
  
