version: '2.1'

services:
  fritzbox_exporter:
    image: fritzbox_exporter
    build: .
    ports:
      - 8765:8765
    environment:
      FRITZ_HOST: fritz.box
      FRITZ_USER: prometheus # needs to be changed
      FRITZ_PASS: prometheus # needs to be changed
